# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
AllCops:
  Exclude:
    - 'vendor/**/*'
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Max: 79
Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
