// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-gem: https://badge.fury.io/rb/renamr.svg
:img-hoc: https://hitsofcode.com/github/rdavid/renamr?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/renamr?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-maintainability: https://api.codeclimate.com/v1/badges/406f1433b0b9e0509a6e/maintainability
:img-rubocop: https://github.com/rdavid/renamr/actions/workflows/rubocop.yml/badge.svg
:img-style: https://img.shields.io/badge/code_style-rubocop-brightgreen.svg
:img-test: https://github.com/rdavid/renamr/actions/workflows/test.yml/badge.svg
:url-cv: http://cv.rabkin.co.il
:url-gem: https://badge.fury.io/rb/renamr
:url-hoc: https://hitsofcode.com/view/github/rdavid/renamr?branch=master
:url-license: https://github.com/rdavid/renamr/blob/master/LICENSES/0BSD.txt
:url-maintainability: https://codeclimate.com/github/rdavid/renamr/maintainability
:url-reuse: https://github.com/fsfe/reuse-action
:url-rubocop: https://github.com/rdavid/renamr/actions/workflows/rubocop.yml
:url-ruby: https://www.ruby-lang.org/en/documentation/installation
:url-style: https://github.com/rubocop/rubocop
:url-test: https://github.com/rdavid/renamr/actions/workflows/test.yml
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Renamr

image:{img-rubocop}[rubocop,link={url-rubocop}]
image:{img-gem}[gem version,link={url-gem}]
// image:{img-maintainability}[maintainability,link={url-maintainability}]
image:{img-style}[code style,link={url-style}]
image:{img-test}[test,link={url-test}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

`renamr` organizes file and directory names.

== Installation
The tool is designed to operate on macOS, GNU/Linux, Windows, and Unix-like
operating systems.
It is packaged as a Gem and requires Ruby version 3.2 or later.
If you do not have the appropriate version on your platform, refer to
{url-ruby}[Installing Ruby].

Utilize this command for installing the package:

[,sh]
----
gem install renamr
----

== Updating

Utilize this command for updating the package:

[,sh]
----
gem update renamr
----

== Usage

[,sh]
----
renamr [options]
  -a, --act          Real renaming.
  -r, --rec          Passes recursively.
  -l, --lim          Limits name length.
  -m, --mod          Prepends modification time.
  -d, --dir dir      Directory to rename.
  -s, --src src      A string to substitute.
  -t, --dst dst      A string to replace to.
  -w, --wid wid      Width of the table.
  -p, --pre str,beg  A string to prepend to started from beg.
  -c, --cut pos,len  Removes len symbols from pos.
  -v, --version      Shows version.
----

== Example

[,sh]
----
renamr -d <source>
----

It renames all files in `source` by default pattern: 26 English letters, 10 numbers, minus for spaces and other symbols.

== License

`renamr` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
