// Settings:
:toc: macro
:!toc-title:
// URLs:
:url-cv: http://cv.rabkin.co.il
:url-license: https://github.com/rdavid/renamr/blob/master/LICENSE
:url-reuse: https://github.com/fsfe/reuse-action
:url-ruby: https://www.ruby-lang.org/en/documentation/installation
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Renamr

image:https://ci.appveyor.com/api/projects/status/cca9iog230smu3k2?svg=true[build,link=https://ci.appveyor.com/project/rdavid/renamr]
image:https://github.com/rdavid/renamr/actions/workflows/rubocop.yml/badge.svg[rubocop,link=https://github.com/rdavid/renamr/actions/workflows/rubocop.yml]
image:https://badge.fury.io/rb/renamr.svg[gem,link=https://badge.fury.io/rb/renamr]
image:https://api.codeclimate.com/v1/badges/406f1433b0b9e0509a6e/maintainability[maintainability,link=https://codeclimate.com/github/rdavid/renamr/maintainability]
image:https://hitsofcode.com/github/rdavid/renamr?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/renamr]
image:https://img.shields.io/badge/code_style-rubocop-brightgreen.svg[ruby style,link=https://github.com/rubocop/rubocop]
image:https://img.shields.io/github/license/rdavid/renamr?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/renamr/blob/master/LICENSE]

toc::[]

== About

`renamr` organizes file and directory names.

== Installation
The tool is designed to operate on macOS, GNU/Linux, Windows, and Unix-like
operating systems.
It is packaged as a Gem and requires Ruby version 2.6 or later.
If you do not have the appropriate version on your platform, refer to
{url-ruby}[Installing Ruby].

Utilize this command for installing the package:

[,sh]
----
gem install renamr
----

== Updating

Utilize this command for updating the package:

[,sh]
----
gem update renamr
----

== Usage

[,sh]
----
renamr [options]
  -a, --act          Real renaming.
  -r, --rec          Passes recursively.
  -l, --lim          Limits name length.
  -m, --mod          Prepends modification time.
  -d, --dir dir      Directory to rename.
  -s, --src src      A string to substitute.
  -t, --dst dst      A string to replace to.
  -w, --wid wid      Width of the table.
  -p, --pre str,beg  A string to prepend to started from beg.
  -c, --cut pos,len  Removes len symbols from pos.
  -v, --version      Shows version.
----

== Example

[,sh]
----
renamr -d <source>
----

It renames all files in `source` by default pattern: 26 English letters, 10 numbers, minus for spaces and other symbols.

== License

`renamr` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
