// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-gem: https://badge.fury.io/rb/renamr.svg
:img-hoc: https://hitsofcode.com/github/rdavid/renamr?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/renamr?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-rake: https://github.com/rdavid/renamr/actions/workflows/rake.yml/badge.svg
:img-rubocop: https://github.com/rdavid/renamr/actions/workflows/rubocop.yml/badge.svg
:img-style: https://img.shields.io/badge/code_style-rubocop-brightgreen.svg
:url-cv: http://cv.rabkin.co.il
:url-gem: https://badge.fury.io/rb/renamr
:url-github: https://github.com/rdavid/renamr
:url-hoc: https://hitsofcode.com/view/github/rdavid/renamr?branch=master
:url-license: https://github.com/rdavid/renamr/blob/master/LICENSES/0BSD.txt
:url-rake: https://github.com/rdavid/renamr/actions/workflows/rake.yml
:url-reuse: https://github.com/fsfe/reuse-action
:url-rubocop: https://github.com/rdavid/renamr/actions/workflows/rubocop.yml
:url-ruby: https://www.ruby-lang.org/en/documentation/installation
:url-style: https://github.com/rubocop/rubocop
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Renamr

[subs=attributes+]
++++
<div align="right">
<a href="{url-rake}"><img src="{img-rake}" alt="rake"></a>
<a href="{url-rubocop}"><img src="{img-rubocop}" alt="rubocop"></a>
<a href="{url-gem}"><img src="{img-gem}" alt="gem version"></a>
<a href="{url-style}"><img src="{img-style}" alt="code style"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/renamr" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

`renamr` normalizes file and directory names.
It rewrites them with lowercase English letters, digits, and hyphens in place
of spaces and other symbols.

== Installation

The tool runs on macOS, GNU/Linux, and other Unix-like operating systems, as
well as Windows.
It is packaged as a Ruby gem and requires Ruby 3.2 or later.
If your platform lacks a suitable Ruby, see {url-ruby}[Installing Ruby].

Install the gem with:

[,sh]
----
gem install renamr
----

== Updating

Update the gem with:

[,sh]
----
gem update renamr
----

== Usage

[,sh]
----
renamr [options]
  -a, --act              Performs actual renaming.
  -c, --cut pos,len      Removes len characters starting at pos.
  -d, --dir dir          Directory to process.
  -l, --lim              Limits file name length.
  -m, --mod              Prepends file modification time.
  -p, --prepend str,beg  Prepends a string.
  -r, --rec              Processes directories recursively.
  -s, --src src          String to replace.
  -t, --dst dst          Replacement string.
  -v, --version          Shows the version.
  -w, --wid wid          Output table width.
----

== Example

[,sh]
----
renamr -d <source>
----

This previews new names for all files in `source` using the default character
set: the 26 English letters, 10 digits, and hyphens in place of spaces and
other symbols.
Adding `-a` performs the actual renaming.

== License

`renamr` is copyright {url-cv}[David Rabkin] and is available under the
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>renamr by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/renamr" target="_blank" rel="noopener">GitHub</a>
    <a href="https://badge.fury.io/rb/renamr" target="_blank" rel="noopener">Gem</a>
    <a href="https://github.com/rdavid/renamr/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
