// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-gem: https://badge.fury.io/rb/renamr.svg
:img-hoc: https://hitsofcode.com/github/rdavid/renamr?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/renamr?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-rake: https://github.com/rdavid/renamr/actions/workflows/rake.yml/badge.svg
:img-rubocop: https://github.com/rdavid/renamr/actions/workflows/rubocop.yml/badge.svg
:img-style: https://img.shields.io/badge/code_style-rubocop-brightgreen.svg
:url-cv: http://cv.rabkin.co.il
:url-gem: https://badge.fury.io/rb/renamr
:url-hoc: https://hitsofcode.com/view/github/rdavid/renamr?branch=master
:url-license: https://github.com/rdavid/renamr/blob/master/LICENSES/0BSD.txt
:url-rake: https://github.com/rdavid/renamr/actions/workflows/rake.yml
:url-reuse: https://github.com/fsfe/reuse-action
:url-rubocop: https://github.com/rdavid/renamr/actions/workflows/rubocop.yml
:url-ruby: https://www.ruby-lang.org/en/documentation/installation
:url-style: https://github.com/rubocop/rubocop
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Renamr

image:{img-rake}[rake,link={url-rake}]
image:{img-rubocop}[rubocop,link={url-rubocop}]
image:{img-gem}[gem version,link={url-gem}]
image:{img-style}[code style,link={url-style}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

`renamr` organizes file and directory names.

== Installation
The tool is designed to operate on macOS, GNU/Linux, Windows, and Unix-like
operating systems.
It is packaged as a Gem and requires Ruby version 3.2 or later.
If you do not have the appropriate version on your platform, refer to
{url-ruby}[Installing Ruby].

Install the gem with:

[,sh]
----
gem install renamr
----

== Updating

Update the gem with:

[,sh]
----
gem update renamr
----

== Usage

[,sh]
----
renamr [options]
  -a, --act              Performs actual renaming.
  -r, --rec              Processes directories recursively.
  -l, --lim              Limits file name length.
  -m, --mod              Prepends file modification time.
  -d, --dir dir          Directory to process.
  -s, --src src          String to replace.
  -t, --dst dst          Replacement string.
  -w, --wid wid          Output table width.
  -p, --prepend str,beg  Prepends a string.
  -c, --cut pos,len      Removes len characters from pos.
  -v, --version          Shows the version.
----

== Example

[,sh]
----
renamr -d <source>
----

It renames all files in `source` using the default character set: 26 English
letters, 10 digits, and hyphens for spaces and other symbols.

== License

`renamr` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
