# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: rake
'on':
  pull_request:
    paths: &paths
      - .github/workflows/rake.yml
      - Gemfile
      - Gemfile.lock
      - Rakefile
      - bin/**
      - lib/**
      - renamr.gemspec
      - test/**
  push:
    branches: [master]
    paths: *paths
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  rake:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26
          - macos-26-intel
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-slim
          - windows-2022
          - windows-2025
          - windows-2025-vs2026
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
          - '4.0'
    name: Rake on ${{ matrix.os }} / Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1.316.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
