# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: rubocop
'on':
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  rubocop:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      checks: write
      contents: read
      pull-requests: write
    env:
      BUNDLE_ONLY: rubocop
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1.317.0
        with:
          ruby-version: 3.2
          bundler-cache: true
      - uses: reviewdog/action-rubocop@v2.22.0
        with:
          reporter: >-
            ${{ github.event_name == 'pull_request'
            && 'github-pr-review' || 'github-check' }}
          fail_level: any
          filter_mode: nofilter
          skip_install: true
          use_bundler: true
