---
name: rubocop
'on':
  pull_request:
    branches: [master]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@d2b39ad0b52eca07d23f3aa14fdf2a3fcc1f411c
        with:
          ruby-version: 2.6
      - name: Install Code Scanning integration
        run: bundle add code-scanning-rubocop --version 0.6.1 --skip-install
      - name: Install dependencies
        run: bundle install
      - name: Rubocop run
        run: |
          bash -c "
            bundle exec rubocop \
              --require code_scanning \
              --format CodeScanning::SarifFormatter \
              -o rubocop.sarif
            [[ $? -ne 2 ]]
          "
      - name: Upload Sarif output
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rubocop.sarif
